# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3eef456575b417b77825eab90b61e983eab5d5e660594a00eeea2054da931ed7d55c417329978bbff8ac375ceaebaa9ea1e07a91f86c237acb2e87d05bce5ce

test:
  secret_key_base: db30d147e35f6c3250201c45c3eacb4bdff29d309752c198d89c1cc2c86e53f75d5fa89d18efca792d2d05b48b1a2ff714acc921b098bae5eff717f829a37595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
